# -------------------
# 1. NAMESPACE
# -------------------
apiVersion: v1
kind: Namespace
metadata:
  name: "2401157"

---
# -------------------
# 2. SERVER (BACKEND) DEPLOYMENT
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: "2401157"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      # --- AUTH FOR NEXUS ---
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: server
        # Matches the Nexus URL from Jenkinsfile
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401157/jobfit-server:v1
        ports:
        - containerPort: 5000
        env:
        # UPDATED WITH YOUR SPECIFIC CREDENTIALS
        - name: MONGO_URL
          value: "mongodb://2401157:anisha@mongodb.imcc.com/jobfit"
        - name: PORT
          value: "5000"

---
# -------------------
# 3. SERVER SERVICE
# -------------------
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: "2401157"
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
# -------------------
# 4. CLIENT (FRONTEND) DEPLOYMENT
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: "2401157"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      # --- AUTH FOR NEXUS ---
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: client
        # Matches the Nexus URL from Jenkinsfile
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401157/jobfit-client:v1
        ports:
        - containerPort: 80